# GitHub Pages 配置
title: Proxmox Clash 插件文档
description: 深度集成到 Proxmox VE Web UI 的 Clash.Meta (mihomo) 原生插件
author: Proxmox Libraries
email: fuqiang.work@proxmox-libraries.com

# 基础 URL 配置
baseurl: "/proxmox-clash-plugin"
url: "https://proxmox-libraries.github.io"

# 主题设置
theme: jekyll-theme-cayman

# 侧边栏配置
show_sidebar: true

# 插件
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 默认布局
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
