name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
    paths: [ 'docs/**', '.github/workflows/docs.yml' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'docs/**', '.github/workflows/docs.yml' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install Jekyll
      run: |
        gem install jekyll bundler
        
    - name: Build Documentation
      run: |
        cd docs
        bundle install
        bundle exec jekyll build --destination ../_site
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '📚 Documentation has been built successfully! You can preview it at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'
          })
